### ISSUE TITLE
Using your jspanel typescript definition file

### ISSUE THREAD

**Issue by UndeadKernel** [UltraVanilla/uvweb#2]
Hey there. I found in your repository a great Typescript definition file for jpanel4. I have been using it and refining it with fixes and additions. Would you mind if I contribute this file (with attribution) to the main jspanel4 repository?

**Comment by lordofpipes** [comment]
Sorry about late response, just now learning that Github screwed up notifications.

Yes, you may use it. As per the header in the file, consider it to be simultaneously licensed under [CC0](https://choosealicense.com/licenses/cc0-1.0/) and [0BSD](https://choosealicense.com/licenses/0bsd/).

Not worried about attribution, it's up to you. If you want to attribute me, `Copyright (c) 2020 lordpipe` would be an appropriate copyright header.
